version: "3.8"
services:
  landuse:
    build: .
    volumes:
      - .:/app
    entrypoint: ./run.sh
  postgres:
    image: "postgis/postgis:13-3.0"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
